export const pageTitles: Record<string, string> = {
  '/dashboard': 'Dashboard',
  '/events': 'Eventos',
  '/events/new': 'Criar Novo Evento',
  '/exhibitors': 'Expositores',
  '/visitors': 'Visitantes',
  '/staff': 'Staff',
  '/suppliers': 'Fornecedores',
  '/permissions': 'Permissões e Perfis',
  '/lectures': 'Palestras',
  '/tracks': 'Trilhas',
  '/activities': 'Atividades',
  '/venues': 'Salas/Locais',
  '/checklist': 'Checklist Geral',
  '/team-tasks': 'Tarefas por Equipe',
  '/registration': 'Credenciamento',
  '/checkin': 'Check-in/Check-out',
  '/access-history': 'Histórico de Acessos',
  '/marketing': 'Marketing e Comunicação',
  '/marketing/ads': 'Ads & Campanhas',
  '/marketing/content': 'Conteúdo',
  '/marketing/email': 'Email Marketing',
  '/marketing/pages': 'Landing Pages',
  '/communication/humangpt': 'HumanGPT',
  '/communication/linkai': 'LinkAI',
  '/communication/notifications': 'Notificações',
  '/analytics': 'Analytics',
  '/analytics/nps': 'NPS',
  '/analytics/heatmap': 'Mapa de Calor',
  '/analytics/engagement': 'Engajamento',
  '/reports': 'Relatórios',
  '/integrations': 'Marketplace de Integrações',
  '/api-management': 'Gerenciamento de APIs',
  '/ai-validator': 'AI Validator',
  '/heatmap': 'HeatmapAI™',
  '/dynamic-pricing': 'Precificação Dinâmica',
  '/legal-ai': 'Legal AI',
};
