// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mizazeckpncdlildjwhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pemF6ZWNrcG5jZGxpbGRqd2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzgzNTksImV4cCI6MjA3Mzk1NDM1OX0.4qJA3NwrwTE_fN2BaPBNJjFefzxaYy6rNfqcD5cqOMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});